#Configuracion del inventario de Libreria_is
#Wed Sep 30 07:58:08 GMT-05:00 2026
exclude.classes=com.universidad.modelo.Profesor
exclude.packages=com.universidad.vista
libraries.blacklist=com.cleandev.tpa.api.TpaRepository,java.sql
