#Project analysis configuration
#Wed Sep 30 01:15:42 COT 2026
exclude.packages=com.universidad.config,com.universidad.controlador,com.universidad.dto,com.universidad.mapeador,com.universidad.modelo,com.universidad.servicio,com.universidad.vista
